### ISSUE TITLE
Support '<' comparision for some blob objects

### ISSUE THREAD

**Issue by bboe** [googleapis/python-storage#66] opened 2020-02-19 19:45 UTC
It would be great to take a list of blob objects, from the same bucket, and sort them lexicographically by name. While it appears that `list_blobs` always returns blobs sorted by name, the [API endpoint documentation](https://cloud.google.com/storage/docs/json_api/v1/objects/list) does not provide any such guarantee. Note, however, that there is such a mention here: https://cloud.google.com/storage/docs/listing-objects.

Unfortunately, without said guarantee on sort order, we provide an explicit sort sometimes when iterating through blobs. Said code ends up looking like this:

```python
for blob in sorted(bucket.list_blobs(), key=lambda blob: blob.name):
    ...
```

While that's not really terrible, it'd be great to more concisely write:

```python
for blob in sorted(bucket.list_blobs()):
    ...
```

Even if the documentation were to guarantee an order for `list_blobs`, it may still be valuable to be able to sort collections of blobs.

Providing such support requires only defining `__lt__` on the bucket object. In fact I've said changes and will link such pull request momentarily.

**Comment by tseaver** [comment] 2020-02-25 21:43
As I noted on your PR, perhaps it would make sense to allow sorting objects across buckets.  @frankyn, WDYT?

**Comment by frankyn** [comment] 2020-04-16 00:41
Hi @bboe, 

Apologies on the delay. How many objects do you have in your bucket? I'd prefer we not support this in the GCS library because `list_blobs()` may be called on a bucket with millions of objects. I think this is better suited in external project code rather than in the Python library.

I'm open to discussing this more, but want to be careful with what the library supports long-term.

**Comment by bboe** [comment] 2020-04-16 03:16
@frankyn thanks for the response. Yes, sorting millions of objects wouldn't be ideal.

Would it be possible to update the documentation to mention that list_blobs is guaranteed to return items sorted by key (assuming that's actually true)?

**Comment by frankyn** [comment] 2020-04-17 04:50
Reaching out to the backend service teams and will get back to you. 

As long as I've used GCS, objects are listed in lexicographical order, but want to confirm because it's a strong statement and want to be careful.

**Comment by frankyn** [comment] 2020-04-20 16:48
Hi @bboe, confirmed with backend team that this is true and not documented appropriately. 

This is being resolved by Technical Writers internally and closing this issue. 
Thanks for your patience @bboe!

**Closed by frankyn** 2020-04-20 16:48 UTC
Labels: api: storage, type: question

**Comment by bboe** [comment] 2020-04-20 17:00
Thanks for following up @frankyn. I appreciate it.
