### ISSUE TITLE
Retry not happening

### ISSUE THREAD

**Issue by nitishxp** [googleapis/python-storage#786] opened 2022-05-09 12:56 UTC
Python 3.9 Cloud function runtime

Lib:
google-cloud-storage==2.1.0

`Error updating data 503 POST https://storage.googleapis.com/upload/storage/v1/b/<bucket_name>?uploadType=resumable: Service Unavailable: ('Request failed with status code', 503, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.CREATED: 201>) Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 2575, in upload_from_file created_json = self._do_upload( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 2393, in _do_upload response = self._do_resumable_upload( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 2218, in _do_resumable_upload upload, transport = self._initiate_resumable_upload( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 2099, in _initiate_resumable_upload upload.initiate( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate return _request_helpers.wait_and_retry( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/resumable_media/requests/_request_helpers.py", line 170, in wait_and_retry raise error File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/resumable_media/requests/_request_helpers.py", line 147, in wait_and_retry response = func() File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request self._process_initiate_response(result) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/resumable_media/_upload.py", line 509, in _process_initiate_response _helpers.require_status_code( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/resumable_media/_helpers.py", line 105, in require_status_code raise common.InvalidResponse( google.resumable_media.common.InvalidResponse: ('Request failed with status code', 503, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.CREATED: 201>) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/workspace/main.py", line 428, in inner func_result = func(*args, **kwargs) File "/workspace/main.py", line 499, in function load_bq_public_data() File "/workspace/main.py", line 294, in load_data storage_blob.upload_from_string(dataFile) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 2848, in upload_from_string self.upload_from_file( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 2592, in upload_from_file _raise_from_invalid_response(exc) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 4464, in _raise_from_invalid_response raise exceptions.from_http_status(response.status_code, message, response=response) google.api_core.exceptions.ServiceUnavailable: 503 POST https://storage.googleapis.com/upload/storage/v1/b/<bucket_name>?uploadType=resumable: Service Unavailable: ('Request failed with status code', 503, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.CREATED: 201>)`

**Comment by ddelgrosso1** [comment] 2022-05-09 14:01
Hi @nitishxp from the stack trace you provided it appears you are attempting to do an upload. Upload operations are not idempotent and by default will not be retried. More information on idempotent operations can be found [here](https://cloud.google.com/storage/docs/retry-strategy#idempotency). You can alter this behavior by making the operation conditionally idempotent (providing a precondition) or by altering the `retry` parameter.

**Comment by nitishxp** [comment] 2022-05-09 15:48
@ddelgrosso1 how to use the existing retry along with passing custom retry method

**Comment by ddelgrosso1** [comment] 2022-05-10 15:27
Since this is expected behavior that can be modified I am going to close this issue. If you feel this does not resolve the issue, please feel free to reopen.

**Closed by ddelgrosso1** 2022-05-10 15:27 UTC
Labels: api: storage, type: question, priority: p2
