### ISSUE TITLE
support for an tf.io.gfile.GFile like API

### ISSUE THREAD

**Issue by kpe** [googleapis/python-storage#354] opened 2020-12-23 14:48 UTC
It would be nice to support a [tf.io.gfile.GFile](https://www.tensorflow.org/api_docs/python/tf/io/gfile/GFile) like API because it can be used as a drop-in replacement for the normal pythonic [`open()`](https://docs.python.org/3/library/functions.html#open) API to transparently handle both local and Google Cloud Storage files (i.e. by using the `gs://` schema).

 **Is your feature request related to a problem? Please describe.**
Well it is much more convinient to use a familiar API like:
```python
filepath = "gs://my-bucket/gcs-file.txt" if True else "/tmp/local-file.txt"
with gcs.GFile(file_path) as f:
  print(f.read())
```
then considering anything like:
```python
#
# how exactly should I read the content of gs://my-buckets/gcs-file.txt 
# - where's the docu?
# - should I read it all?
# - I just need to read a text file (from GCS)
#
from google.cloud import storage
from google.cloud.storage.blob import Blob
client = storage.Client()
blob = Blob.from_string("gs://my-buckets/gcs-file.txt")
blob.download_as_*** # ... agghhh.h.. I'll just give up
```

 **Describe the solution you'd like**
The way acess to GCS buckets is handled in TF (i.e. `tf.io.gfile.GFile`) is just perfect, however if I only need GCS file access, I may not want to install all of tensorflow. 

 **Describe alternatives you've considered**
As an alternative one could try splitting `tf.io.gfile.GFile` into a standalone pip package.

I'm not sure if this is the right place for a feature request like that, but it would be nice if there is a some pyton ideomatic `open()` like API. And if it were there, I guess, it would be used 90% of the time.

**Comment by frankyn** [comment] 2021-01-05 18:18
Thanks @kpe, this is a duplicate of: https://github.com/googleapis/python-storage/issues/29

@andrewsg is working on a solution.

**Closed by frankyn** 2021-01-05 18:18 UTC
Labels: api: storage, type: feature request
