### ISSUE TITLE
Also cannot import name urllib

### ISSUE THREAD

**Issue by YChebotaev** [googleapis/python-storage#112] opened 2020-04-20 23:11 UTC
(Ya, I know that's duplicate of googleapis/google-api-python-client#42 but I don't get any solution there)

macOS High Sierra 10.13.6
Python 2.7.10
pip 20.0.2

google-api-core==1.17.0
google-auth==1.14.0
google-cloud-core==1.3.0
google-cloud-storage==1.22.0
google-resumable-media==0.4.1
googleapis-common-protos==1.51.

#### Steps to reproduce

  1. Make a file with following content:
```python
from google.cloud import storage
```

Error I have:

```shell
    from six.moves import urllib
ImportError: cannot import name urllib
```

**Comment by busunkim96** [comment] 2020-04-21 16:54
Would you mind trying to install the library in a clean virtual environment?

```sh
python3 -m venv env
source env/bin/activate
python3 -m pip install google-cloud-storage
```

**Comment by YChebotaev** [comment] 2020-04-21 19:34
> Would you mind trying to install the library in a clean virtual environment?

It worked, but I cannot use venv and I cannot use python3.

I need exact versions like described.

**Comment by YChebotaev** [comment] 2020-04-24 19:15
@busunkim96 Hey? Any help on this?

**Comment by YChebotaev** [comment] 2020-04-26 18:41
Help?

**Comment by HemangChothani** [comment] 2020-04-27 07:21
@YChebotaev  Could you please share the version of  `six` library. I think you need to upgrade the version of  `six` library and also try with upgraded the version of  `urllib3`

**Comment by YChebotaev** [comment] 2020-04-27 14:49
@HemangChothani 

```six==1.14.0
urllib3==1.25.9```

Both the latest versions/

**Comment by HemangChothani** [comment] 2020-04-28 06:54
@YChebotaev  I am not able to reproduce it, it might be related to the conflict of `six` lib versions. Try to find [other copy](https://github.com/googleapis/google-api-python-client/issues/42#issuecomment-323121983)of `six` it will help if multiple versions is installed.

Would you mind trying to install the libraries in a new virtual environment of python 2.7 with specific versions which mentioned above in comment?

**Comment by YChebotaev** [comment] 2020-05-09 05:29
@HemangChothani 
Thank You for trying but I workaround this problem with custom solution.

Sad to see that official library fail to work on 2.7 environment.

**Comment by HemangChothani** [comment] 2020-05-11 06:30
@YChebotaev Would you please try with the fresh environment and few steps, it would be helpful to resolve or close the issue as it's work for me with python 2.7.

Please check the versions of the following libs at the runtime and also check the installed paths.

    import six
    six.__version__    #'1.14.0'
    
    from google.cloud import storage
    storage.__version__   #'1.22.0'

**Comment by YChebotaev** [comment] 2020-05-12 05:56
@HemangChothani 
First two lines are same: `six.__version__ === "1.14.0"`

But 4th one is giving error: `from google.auth import environment_vars`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/apsmav/Library/Python/2.7/lib/python/site-packages/google/cloud/storage/__init__.py", line 38, in <module>
    from google.cloud.storage.batch import Batch
  File "/Users/apsmav/Library/Python/2.7/lib/python/site-packages/google/cloud/storage/batch.py", line 29, in <module>
    from google.cloud import _helpers
  File "/Users/apsmav/Library/Python/2.7/lib/python/site-packages/google/cloud/_helpers.py", line 31, in <module>
    import google.auth
  File "/Users/apsmav/Library/Python/2.7/lib/python/site-packages/google/auth/__init__.py", line 19, in <module>
    from google.auth._default import default
  File "/Users/apsmav/Library/Python/2.7/lib/python/site-packages/google/auth/_default.py", line 28, in <module>
    from google.auth import environment_vars
```

**Comment by HemangChothani** [comment] 2020-05-12 06:38
@YChebotaev Could you share the full trace and error type like it's import error or any other?

**Comment by YChebotaev** [comment] 2020-05-12 20:10
@HemangChothani 
Yes, it after I type `from google.cloud import storage`.

Don't sure what You call import error, but, Yes, it occurs when I import `storage` from `google.cloud`.

**Comment by HemangChothani** [comment] 2020-05-13 11:18
@YChebotaev This error is weird, related to google-auth library. Please check the file `environment_vars.py` file is exist on your path `"/Users/.../Library/Python/2.7/lib/python/site-packages/google/auth/` or not.

Or you can reinstall google_auth lib or google-cloud-storage library and verify it, then try to run it.

**Comment by YChebotaev** [comment] 2020-05-15 13:56
@HemangChothani 
Yes, `environment_vars.py ` exists by given path.

Well, I definitely can "just reinstall" this but I'm not alone in this project and I can't force everyone "just reinstall" everything. The library must work out-of-the-box without extra steps.

**Comment by HemangChothani** [comment] 2020-05-15 14:06
@YChebotaev I have tried with many combinations but not able to reproduce it, and the your recent error is also related to google-auth package so to verify everything, you need to reinstall google-auth and google-cloud storage or you can check with fresh environment of python2.7.
I think something has broken in your library dependencies.

**Comment by YChebotaev** [comment] 2020-05-16 09:02
@HemangChothani I'm installed `google-cloud-storage` version 1.22.0 via pip via `dependencies.txt`. This is standard process for dependencies in many teams. Every other library works fine this way.

**Comment by HemangChothani** [comment] 2020-05-18 06:55
@YChebotaev I saw your comment [here](https://github.com/googleapis/google-api-python-client/issues/42#issuecomment-615538889), You can see here https://pypi.org/project/google-cloud-storage/ that latest version of  `google-cloud-storage`  is also supports `python 2.7`, so you can upgrade `google-cloud-storage` and try it.

**Comment by HemangChothani** [comment] 2020-05-18 13:15
@YChebotaev If you are still facing the issue then something is missing in you given traceback which you have given [above](https://github.com/googleapis/python-storage/issues/112#issuecomment-627127000) , because `environment_vars.py` file doesn't import six module.

**Comment by HemangChothani** [comment] 2020-06-01 07:18
@YChebotaev any update from your side?

**Comment by YChebotaev** [comment] 2020-06-02 05:52
Not really. I crafted a perfectly working custom solution for my case without this library and I don't want to do additional work.

I will try this library again when I need to rely on GCS and leave note here.

Thank You for Your attention.

**Closed** 2020-06-15 08:41 UTC
Labels: api: storage, needs more info, type: question
