### ISSUE TITLE
storage.Client.list_blobs limits results to 1000 when using the `fields` option

### ISSUE THREAD

**Issue by teije01** [googleapis/python-storage#977] opened 2023-01-19 16:31 UTC
The amount of blobs returned by the `storage.Client.list_blobs` depends on the `fields` argument. 

If it is provided, then a maximum of 1000 results were returned. If it is omitted, then the actual amount of blobs is returned.
Moreover, if both the `fields` and the `max_results` were provided, then a maximum of 5000 blobs were obtained

#### Environment details

  - OS type and version: `Linux 8h488h2 5.13.0-35-generic #40~20.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux`
  - Python version: `3.7.12`
  - pip version: `20.2.4`
  - `google-cloud-storage` version: `2.0.0`

#### Code example

```python

bucket_name = "mybucket"

storage_client = Client()
bucket = storage_client.get_bucket(bucket_name)

blob_iterator = storage_client.list_blobs(
            bucket,
            max_results=None,
)
blobs_no_fields = list(blob_iterator)  # no maximum

blob_iterator = storage_client.list_blobs(
            bucket,
            max_results=None,
            fields="items(name)",
)
blobs_fields = list(blob_iterator)  # 1000 maximum

blob_iterator = storage_client.list_blobs(
            bucket,
            max_results=10_000,
            fields="items(name)",
)
blobs_fields_and_max_results = list(blob_iterator)  # 5000 maximum
```

#### Expected behavior

blob_iterator = storage_client.list_blobs(
            bucket,
            max_results=None,
            fields="items(name)",
)
blobs_no_fields = list(blob_iterator)  # no maximum

**Comment by cojenco** [comment] 2023-01-19 23:34
Hi @teije01 thank you for the question. I ran a few tests locally. Try adding `nextPageToken` to `fields`, as below. With this change I was successful in making the request with no results limits.
```
blob_iterator = storage_client.list_blobs(
            bucket,
            max_results=10_000,
            fields="nextPageToken, items(name)",
)
```

The `fields` request parameter specifies the fields you want returned, as noted in the [partial response](https://cloud.google.com/storage/docs/json_api#partial-response) section in the docs. Without a nextPageToken returned, the iterator cannot fetch the remaining items.

**Comment by teije01** [comment] 2023-01-20 08:45
Thank you very much @cojenco , I can confirm that your provided solution works for me.

Although I understand the behavior, I still find it somewhat unexpected. I assumed that the pagination would be fully handled by the internals of the storage client. Now looking at the docstring, I do indeed see `nextPageToken` stated there, and this is the exact behavior of the object listing endpoint.

In an attempt to speed up the requests, I ended up limiting the amount of results obtained. What may be considered is adding the nextPageToken by default, since it should have no meaningful impact on performance, and might prevent other users from experiencing the same problems. If this is unacceptable, perhaps expanding the docstring with the warning that pagination is disabled when `nextPageToken` is not provided in fields.

**Comment by cojenco** [comment] 2023-01-31 23:31
Including `nextPageToken` in fields is noted and demonstrated in the `fields` docstring for relevant list operations, for instance, in [client.list_blobs()](https://github.com/googleapis/python-storage/blob/main/google/cloud/storage/client.py#L1178-L1184).

Checked internally and this is working as intended following API design. Closing for now; Please reopen if you'd still like to discuss further. Thank you for reaching out!

**Closed by cojenco** 2023-01-31 23:31 UTC
Labels: api: storage, type: question, priority: p2
