### ISSUE TITLE
Storage: Bucket not including Access-Control-Allow-Origin header in preflight OPTIONS response

### ISSUE THREAD

**Issue by danjenson** [googleapis/python-storage#3] opened 2020-01-30 03:05 UTC
Fedora 31, Google Chrome 79. 

On python 3.7 flask server:
```
from google.cloud import storage
store = storage.Client.from_service_account_json('service_account.json')
bucket = store.create_bucket('test')
cors = bucket.cors
cors.append({'origin': ['*']})
bucket.cors = cors
bucket.update()
```
Command line cors check:
```
gsutil cors get gs://test  # [{"origin": ["*"]}]
```

On client in JS:
```
# uploadUri is a signed uri from the 'test' bucket for uploading (PUT requests, v4)
# file is a local filesystem file
fetch(uploadUri, {
  method: 'PUT',
  mode: 'cors',
  cache: 'no-cache',
  headers: {
    'Content-Type': 'application/octet-stream',  # same error with file.type
  },
  body: file,
}).then(() => console.log('success'));
```
When this is sent, it runs a preflight OPTIONS request, which does not return the `Access-Control-Allow-Origin` header in the response, so the PUT fails.

Response headers include: alt-svc, cache-control, content-length, content-type, date, expires, server, status, vary, x-guploader-uploadid.

It looks like the signed URL uses the XML API by default, since the url is `https://storage.googleapis.com/[BUCKET-NAME]/[PATH-NAME]?<signed_url_params>` (https://cloud.google.com/storage/docs/request-endpoints), which is why I set the CORS above according to the documentation.

This happens locally, and while hosted on app engine. It also happens with both the fetch API and Axios npm package.

I've also tried adding maxAgeSeconds = 3600, method = ['*'], and 'Access-Control-Allow-Origin' to the 'responseHeader' array. Problem persists on retry, even several hours later.

Upload from command line using curl works: `curl -v -I -X PUT -T file.csv -H 'Content-Type: application/octet-stream' <signed_url>`, so this appears to be a browser/cors/headers issue.

I believe I have gone through and checked everything here: https://cloud.google.com/storage/docs/configuring-cors.

**Comment by HemangChothani** [comment] 2020-02-03 05:50
@danjenson not that much familiar with the nodejs , so could you please share you code snippet like which part you used with nodejs (from browser) and which through the flask(python).

**Comment by HemangChothani** [comment] 2020-02-03 09:43
@danjenson  sorry for the mess, surely this will help you please visit this [link](https://cloud.google.com/functions/docs/writing/http#handling_cors_requests).

**Comment by HemangChothani** [comment] 2020-02-03 10:56
@crwilcox  Please comment on this, For the   `OPTIONS`  request , backend should return the `Access-Control-Origin` header or what i share a [link](https://cloud.google.com/functions/docs/writing/http#handling_cors_requests) is the only option to handle cors.

**Comment by danjenson** [comment] 2020-02-03 16:49
It looks like that link is for Cloud Functions? I need to set CORS on my storage bucket, and I'm using the instructions here: https://googleapis.dev/python/storage/latest/buckets.html (search for 'cors')

**Comment by HemangChothani** [comment] 2020-02-04 07:10
@crwilcox This is back-end issue,so can you filed issue as internal issue.

**Comment by danjenson** [comment] 2020-02-05 02:25
Is there any chance this will be resolved in the next few weeks? We're a team a Stanford that is planning on releasing a platform for data journalism next month at our big conference. However, a key element of that is having users be able to upload large datasets from the website. If it's unlikely this will be resolved, we need to investigate other platforms.

**Comment by danjenson** [comment] 2020-02-10 23:57
@HemangChothani, any word?

**Comment by HemangChothani** [comment] 2020-02-11 06:47
@frankyn  @crwilcox  could you please comment or any suggestion.

**Comment by frankyn** [comment] 2020-02-11 18:57
Hi folks, 

Thanks for the ping @HemangChothani.

I reviewed the Storage documentation. I have a short question while I dig into this as nothing stands out right now.

In documentation:
> If you're not seeing a request and response, it is possible that your browser has cached an earlier failed preflight request attempt. Clearing your browser's cache should also clear the preflight cache.

Have you attempted to clear your browser cache @danjenson? I understand that cache-control is private and maxAge is 0.
Apologies if this is not very helpful but I'm taking a look and want to make sure this isn't the case.

**Comment by danjenson** [comment] 2020-02-12 05:31
Yes, countless times. I also used incognito since it shouldn't store that information

**Comment by danjenson** [comment] 2020-02-13 02:08
Out of curiosity, why was this downgraded? Seems like being able to upload a file to cloud storage from a browser is a pretty important use case? Right now we're switching to flexible instances on app engine so we can increase the memory so users can upload to the server and then we upload from the server to storage. This is clearly not ideal and will probably cost us a non trivial amount since our users could be uploading up to 10gb files (which we'd rather have go straight to storage).

**Comment by danjenson** [comment] 2020-02-18 16:00
Any progress on this?

**Comment by frankyn** [comment] 2020-02-21 05:59
Bumping priority on this. It's in my queue but don't have an update at this time apologies for the delay @danjenson.

**Comment by jkwlui** [comment] 2020-02-21 21:54
A shorted update - I've reached out to the service team since it appears to me this could have been a backend issue with the bad preflight request. I'll respond once we got a response from them.

@danjenson We're sorry for the delay and I appreciate your patience while we work to resolve this.

**Comment by danjenson** [comment] 2020-03-17 17:47
Has this been remedied?

**Comment by frankyn** [comment] 2020-03-18 17:02
Hi @danjenson, it's a work in progress and we are speaking with the service team. We appreciate your patience.

**Comment by jkwlui** [comment] 2020-03-30 20:17
@danjenson, can you try adding `"responseHeader": ["*"]` to your bucket's CORS config?

**Comment by AnuroopSuresh** [comment] 2020-04-03 08:30
hello, facing the same issue. 'gsutil cors get gs://...' output:
```
[{"maxAgeSeconds": 3600, "method": ["*"], "origin": ["*"], "responseHeader": ["*"]}]
```
my NodeJs Code:
```
async function generateV4UploadSignedUrl(filename, mimeType, expiryInMs) {
    // These options will allow temporary uploading of the file with outgoing
    // Content-Type: application/octet-stream header.
    const options = {
        version: 'v4',
        action: 'write',
        //expires: Date.now() + 1000 * 60 * expiryInMins, // 15 minutes
        expires: expiryInMs,
        contentType: mimeType,
    };

    // Get a v4 signed URL for uploading file
    const [url] = await bucket
        .file(filename)
        .getSignedUrl(options);

    console.log(`curl -X PUT -H 'Content-Type: ${mimeType}' --upload-file ${filename} '${url}'`);
    return url;
}
```

browser response:
```
alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,h3-T050=":443"; ma=2592000
cache-control: private, max-age=0
content-length: 267
content-type: application/xml; charset=UTF-8
date: Fri, 03 Apr 2020 08:23:57 GMT
expires: Fri, 03 Apr 2020 08:23:57 GMT
server: UploadServer
status: 400
x-guploader-uploadid: AEnB2UqUuAZ-giq_ljMBwLrXNN5SRZHKwb12jI-uhhXU4oXczdEzjnZLjyOxXS3pQxYb3dUWG508_jui--wrM4xAnjQhGT33Mg
```
No. Access-control-allow-origin header. Plz any update. ??

**Comment by danjenson** [comment] 2020-04-08 17:24
Same, any update? This is taking quite a while for a p1 bug. We can't load anything on our domain/website directly from storage due to this issue.

**Comment by jkwlui** [comment] 2020-04-10 00:44
Hi, @danjenson. Again we apologize for the delay. If this is a PUT request, you shouldn't need to deal with resumable headers.

Here's a set of steps that worked for me:

```json
[{
        "origin": [
                "*"
        ],
        "responseHeader": [
                "Content-Type",
                "x-goog-resumable"
        ],
        "method": [
                "PUT",
                "POST"
        ],
        "maxAgeSeconds": 3600
}]
```

```shell
$  gsutil cors set cors.json gs://bucket-name
```

generate_signed_url.py
```python3
import datetime
import sys
from google.cloud import storage

bucket_name = sys.argv[1]

store = storage.Client()
bucket = store.bucket(bucket_name)
blob = bucket.blob('test.txt')
signed_url = blob.generate_signed_url(expiration=datetime.timedelta(days=1), version='v4',scheme='https',method='PUT')

cmd = 'curl -v -i -X OPTIONS -H "Origin: hello.com" -H "Access-Control-Request-Method: PUT" -H "Access-Control-Request-Headers: Content-Type" {}'.format(signed_url)

print(cmd)
```

Then run `python generate_signed_url.py <bucket-name>`, which returns a curl command that makes an OPTIONS request. Run the curl command.

curl returns CORS response headers as expected:
```
< access-control-allow-methods: PUT,POST
access-control-allow-methods: PUT,POST
< access-control-allow-headers: Content-Type,x-goog-resumable
access-control-allow-headers: Content-Type,x-goog-resumable
```

Using the signed URL in the browser with the Fetch API also worked for me:
```html
<script>
const url = '<insert signed url from python script>';
fetch(url, {
    method: 'PUT',
});
</script>
```

<img width="1064" alt="Screen Shot 2020-04-09 at 5 32 15 PM" src="https://user-images.githubusercontent.com/4001432/78951805-3dd91800-7a88-11ea-8e56-c4d7211ae3a4.png">

**Comment by dharanidhar-reddy** [comment] 2020-04-21 17:22
Hi @jkwlui, Do you have any update on the issue? We are also facing it.
`gsutil cors get gs://...`
`[{"maxAgeSeconds": 3600, "method": ["PUT"], "origin": ["*"], "responseHeader": ["Authorization, Content-Range, Accept, Content-Type, Origin, Range"]}]`
This worked for some time. 

![Screenshot from 2020-04-16 19-29-05](https://user-images.githubusercontent.com/36027421/79892706-8c8b9800-8420-11ea-8da1-392b83b6107f.png)

But now we are not even getting the configured response headers.

![Screenshot from 2020-04-21 22-37-32](https://user-images.githubusercontent.com/36027421/79892828-b93faf80-8420-11ea-8ea4-d22c4748181c.png)

**Comment by jkwlui** [comment] 2020-04-21 17:50
@dharanidhar-reddy Thanks for the additional information. One question - do you have an estimate of how long did it work until it failed again?

**Comment by dharanidhar-reddy** [comment] 2020-04-21 18:01
> @dharanidhar-reddy Thanks for the additional information. One question - do you have an estimate of how long did it work until it failed again?

I'm not really sure about how much time it worked. I worked on APR 16 and we checked a couple of hours ago and it didn't work.

**Comment by kilianstallz** [comment] 2020-04-28 13:35
Same issue here, @danjenson 

So we too generate a signed url using our backend API like this:
```javascript
const [url] = await this.storage.bucket(bucketName).file(filename).getSignedUrl({
            action: 'write',
            version: 'v4',
            contentType: filetype,
            expires: Date.now() + 15 * 60 * 1000, // 15minutes
        })
````
we are using this CORS policy for testing purposes:
````json
[{"origin": ["*"],"responseHeader": ["*"],"method": ["*"],"maxAgeSeconds": 3600}]
````

This did not work using the browsers Fetch API, we switched to simple XHR-Requests like this:

````javascript
const signedURL = getSingedURL()
const xhr = new XMLHttpRequest()
    xhr.open('PUT', res.data.createUploadURL, true)
    xhr.onload = () => {
      const status = xhr.status
      if (status === 200) {
        console.log('uploaded')
      } else {
        alert('WRONG!')
      }
    }
    xhr.onerror = () => {
      alert('ERROR')
    }
    xhr.setRequestHeader('Content-Type', this.file?.type as string)
    xhr.send(this.file)
`````

works perfectly for us!

**Comment by BrandonY** [comment] 2020-04-29 19:06
I have been trying to reproduce this problem but have so far been been unsuccessful. All of the CORS preflight requests I've tried have returned correct CORS headers (or not, should the request not be acceptable according to the bucket's policy). There can be up to a 30 second delay while new CORS policies propagate, which is expected, but asides from that I haven't seen any oddities.

Can anyone who still sees it either provide careful reproduction steps or perhaps a fairly long-lived signed URL that I could try invoking?

**Comment by AnuroopSuresh** [comment] 2020-04-30 09:47
```
[
  {
    "origin": ["<yourOrigin>"],
    "method": ["OPTIONS", "PUT"],
    "responseHeader": [
      "Content-Type",
      "Access-Control-Allow-Origin",
      "X-Requested-With"
    ],
    "maxAgeSeconds": 3600
  }
] 
```
Please try with this CORS header

https://github.com/googleapis/nodejs-storage/issues/1145

it worked for me

**Comment by HemangChothani** [comment] 2020-04-30 14:09
@danjenson Could please confirm that  given solution from [AnuroopSuresh](https://github.com/googleapis/python-storage/issues/3#issuecomment-621729811)  is  working for you or not . 
It worked for me as well.

**Comment by govindrai** [comment] 2020-04-30 19:27
@danjenson I dunno if this will help, but I ran into this and spent about 6 hours on it. Here's what was happening for me: 

I tried to upload an image with a signed url. That request would return a CORS error in Chrome devtools stating that dreaded `no "ACCESS_CONTROL_ALLOW_METHODS" headers were present..`. Since Chrome has taken out OPTIONS requests visibility on chrome 79+, I used a tool called HTTP Toolkit tool to intercept look at exactly what the OPTIONS request was returning. The options request was, in fact, returning the right headers, however, the signed request was returning a 403 with a body of `Invalid Signature, the signature you calculated is not correct..`. Chrome for whatever reason was combining the two requests into a CORS errors which is not the case, very frustrating. 

Turns out, I had a logic issue and was calculating the signature with the incorrect action. You might want to use HTTP toolkit to intercept your browser activity and see what is actually going on with those supposed "CORS" errors. 

If that doesn't help, good luck!

**Comment by kikoanis** [comment] 2020-05-09 20:23
After spending few hours on the cors issue, here is what worked for me. 

Google Storage Server CORS settings:
```
     "responseHeader": ["Content-Type", "Access-Control-Allow-Origin", "X-Requested-With", "x-goog-resumable"],
     "method": ["PUT", "POST"],
     "maxAgeSeconds": 3600


Do not include any thing in your request other than the file buffer/stream in the put signed url request. No authorization header nor any other headers, only the content type (which is file type 'image/jpeg' for images for instance).
Every time you make a change, you need to clear browser cache. That is essential as you may get a previous response.

Hope this helps.

**Comment by mlescaudron** [comment] 2020-05-17 13:55
@danjenson, thank you, I can confirm that it is not a cors issue but just an error from Chrome.

![image](https://user-images.githubusercontent.com/9129639/82148822-41866880-9898-11ea-85ed-39c8a6349dae.png)

I had a typo issue. Here is what the function is expecting > 
![image](https://user-images.githubusercontent.com/9129639/82149072-7e069400-9899-11ea-840a-fbb60eff9ae0.png)

From browser >
![image](https://user-images.githubusercontent.com/9129639/82149057-6cbd8780-9899-11ea-8b34-6b8a8c9b2160.png)

To GCP > 
![image](https://user-images.githubusercontent.com/9129639/82149094-9a0a3580-9899-11ea-99fa-2cc602ff3d01.png)

Code > 
![image](https://user-images.githubusercontent.com/9129639/82149135-dc337700-9899-11ea-993a-0ffbcba1963b.png)

**Comment by mohsinkhansymc** [comment] 2020-07-30 13:33
@danjenson i dont know if you have resolved this but the response headers need to match your `access-control-request-headers` so in your case you only need contenttype in there.  try using this and test, this should fix your preflight  call :crossed_fingers: 
`[{
        "origin": [
                "*"
        ],
        "responseHeader": [
                "Content-Type"
        ],
        "method": [
                "PUT",
                "POST"
        ],
        "maxAgeSeconds": 3600
}]`

**Comment by HemangChothani** [comment] 2020-08-06 06:07
@danjenson Can we close this issue?

**Comment by danjenson** [comment] 2020-08-11 04:03
Sorry, we've moved on from this for now.

**Comment by HemangChothani** [comment] 2020-08-11 06:16
Closing this issue for now as many users suggested the solution and agreed with it , feel free to reopen if it happen again.

**Closed by HemangChothani** 2020-08-11 06:16 UTC
Labels: api: storage, external, triage me, type: bug

**Comment by jfbrennan** [comment] 2020-10-27 17:49
Had this issue and like @mlescaudron has shown, it's because Chrome is swallowing up the actual response and logging a somewhat misleading error about CORS. 

I say somewhat misleading because it appears the error response does not have the proper CORS headers even though they've been properly set via gsutil. In my case I did not know about the need to send a `x-goog-content-sha256` header in the request (and whitelist it in my CORS config). Once I did that, the request was successful. Removing that header from the request and it goes right back to the misleading CORS error in Chrome.

**Comment by hendrikfrentrup** [comment] 2020-11-09 08:41
This issue is closed pre-maturely and it looks to me the issue lies with Google's backend - not Chrome or anything else.

Here is why:
CORS is a *browser* security feature hence the issue arises with AJAX requests. The objective for most will be to upload a fairly large file to a Google Storage bucket directly without going through an app server. The app server is used to provide the signed URL to upload directly to the GS bucket, akin to the initial `POST` request described in Google's docs [here](https://cloud.google.com/storage/docs/performing-resumable-uploads). The app server generates the signed URL via Google's API and returns it to the client.

This is when the crucial part of the upload starts. The docs describe a `PUT` request via curl - but most apps run in a browser so we create an AJAX PUT request (`Content-Length` is by default populated by the browser).

```
let file = $("#file-input")[0].files[0]
fetch(<signed_url>,
    {
        method: 'PUT',
        body: file
    })
```

Now CORS kicks in, so I've set the following CORS configuration on the bucket:

```
[
  {
    "origin": ["*"],
    "method": ["PUT", "OPTIONS"],
    "responseHeader": [
        "Content-Type",
        "Access-Control-Allow-Origin"
    ],
    "maxAgeSeconds": 60
  }
]
```

It sends a preflight request (`method: OPTIONS`) - as per specification it contains the `origin` header, e.g. for something running locally: `origin: http://localhost:8080`. This preflight request is successful and returns with status 200 and the following headers:
```
access-control-allow-headers : content-type
access-control-allow-methods : PUT
```

Then, the actual `PUT` request gets fired off. **The crucial point is that this request also runs successfully and returns with status 200** (the payload is also saved to the bucket!) *BUT* the response does not contain the `Access-Control-Allow-Origin` header. And that is what the browser is expecting according to [the specs](https://fetch.spec.whatwg.org/#http-responses). The browser therefore drops the response payload and throws the error.

I would expect that if I specifically set my CORS config for `origin` via `gsutil` (see GCS [docs](https://cloud.google.com/storage/docs/configuring-cors)) to `'*'` or a specific domain (`http://localhost:8080` should also work!), then the response from the GCS bucket would include it in its response header. For example, a request fired off from a script hosted at `myapp.appspot.com` would pass CORS when the domain is included in the `origin` value of the configuration.

What do the folks at Google think about this? Might someone have mocked around with the headers that get sent back? CORS is a security feature, so it should work well and specs should be adhered to (especially when they are described in detail in your [docs](https://cloud.google.com/storage/docs/configuring-cors)).

**Comment by sebelik** [comment] 2021-04-16 18:37
I am seeing similar behavior as @hendrikfrentrup.

In my case, the server provides the signed URL directly to the client to start a resumable upload. The client performs an empty `POST` request to the signed URL to receive a session URL. For this initial request, CORS works fine -  the client receives `Access-Control-...` headers for **both the preflight `OPTIONS` request and the `POST` request**. So far so good.

However, when the client tries to upload the individual file chunks, things break. The resumable upload is a series of `PUT`s (with an appropriate `Content-Range` value) to the session URL received in response to the first `POST`. For these `PUT` requests, however, **the preflight response contains the CORS headers, but the `PUT` response itself does not** causing the browser to throw an error. 

All of this happens on the client, so the `Origin` header is exactly the same for all of these requests. So it seems there's something wrong with the way GCS is handling CORS specifically for `PUT` requests to these session URLs.

Here's the CORS configuration on my bucket:
```
[
  {
    "origin": [ "*" ],
    "method": ["DELETE", "GET", "HEAD", "POST", "PUT", "PATCH"],
    "responseHeader": ["Content-Type", "Content-Length", "Content-Range", "Access-Control-Allow-Origin", "X-Requested-With", "X-Goog-Resumable"],
    "maxAgeSeconds": 360
  }
]
```
