### ISSUE TITLE
Attempting to download blob from private bucket using anonymous client throws an opaque error

### ISSUE THREAD

**Issue by llarco** [googleapis/python-storage#94] opened 2020-04-01 00:45 UTC
#### Environment details

  - OS type and version: debian9
  - Python version: 2.7.13
  - pip version: 9.0.1
  - `google-cloud-storage` version: 1.26.0

#### Steps to reproduce

1. Upload a file into a private bucket
2. Run code below

#### Code example

```python
storage_client = storage.Client.create_anonymous_client()
bucket = storage_client.bucket(bucket_name)
blob = bucket.blob(blob_name)
blob.download_to_filename(file_name)
```

#### Stack trace
```
Traceback (most recent call last):
  File "/home/makani/.cache/bazel/_bazel_makani/66a73d4038f98ebb267a10bd0dbd650c/execroot/makani/bazel-out/host/bin/lib/bazel/gcs_fetch.runfiles/makani/lib/bazel/gcs_fetch.py", line 61, in DownloadFileIfNecessary
    blob.download_to_filename(file_name)
  File "/home/makani/.cache/bazel/_bazel_makani/66a73d4038f98ebb267a10bd0dbd650c/execroot/makani/bazel-out/host/bin/lib/bazel/gcs_fetch.runfiles/python_pip_pypi__google_cloud_storage_1_26_0/google/cloud/storage/blob.py", line 783, in download_to_filename
    raw_download=raw_download,
  File "/home/makani/.cache/bazel/_bazel_makani/66a73d4038f98ebb267a10bd0dbd650c/execroot/makani/bazel-out/host/bin/lib/bazel/gcs_fetch.runfiles/python_pip_pypi__google_cloud_storage_1_26_0/google/cloud/storage/blob.py", line 743, in download_to_file
    transport, file_obj, download_url, headers, start, end, raw_download
  File "/home/makani/.cache/bazel/_bazel_makani/66a73d4038f98ebb267a10bd0dbd650c/execroot/makani/bazel-out/host/bin/lib/bazel/gcs_fetch.runfiles/python_pip_pypi__google_cloud_storage_1_26_0/google/cloud/storage/blob.py", line 667, in _do_download
    download.consume(transport)
  File "/home/makani/.cache/bazel/_bazel_makani/66a73d4038f98ebb267a10bd0dbd650c/execroot/makani/bazel-out/host/bin/lib/bazel/gcs_fetch.runfiles/python_pip_pypi__google_resumable_media_0_5_0/google/resumable_media/requests/download.py", line 151, in consume
    result = _helpers.http_request(transport, method, url, **request_kwargs)
  File "/home/makani/.cache/bazel/_bazel_makani/66a73d4038f98ebb267a10bd0dbd650c/execroot/makani/bazel-out/host/bin/lib/bazel/gcs_fetch.runfiles/python_pip_pypi__google_resumable_media_0_5_0/google/resumable_media/requests/_helpers.py", line 136, in http_request
    return _helpers.wait_and_retry(func, RequestsMixin._get_status_code, retry_strategy)
  File "/home/makani/.cache/bazel/_bazel_makani/66a73d4038f98ebb267a10bd0dbd650c/execroot/makani/bazel-out/host/bin/lib/bazel/gcs_fetch.runfiles/python_pip_pypi__google_resumable_media_0_5_0/google/resumable_media/_helpers.py", line 150, in wait_and_retry
    response = func()
  File "/home/makani/.cache/bazel/_bazel_makani/66a73d4038f98ebb267a10bd0dbd650c/execroot/makani/bazel-out/host/bin/lib/bazel/gcs_fetch.runfiles/python_pip_pypi__google_auth_1_12_0/google/auth/transport/requests.py", line 473, in request
    self.credentials.refresh(auth_request)
  File "/home/makani/.cache/bazel/_bazel_makani/66a73d4038f98ebb267a10bd0dbd650c/execroot/makani/bazel-out/host/bin/lib/bazel/gcs_fetch.runfiles/python_pip_pypi__google_auth_1_12_0/google/auth/credentials.py", line 148, in refresh
    raise ValueError("Anonymous credentials cannot be refreshed.")
ValueError: Anonymous credentials cannot be refreshed.
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by frankyn** [comment] 2020-04-01 19:14
Thanks @llarco to be clear, you mentioned using a large object size, could you provide a file size that you found to be consistent to repro this issue?

**Comment by llarco** [comment] 2020-04-01 20:16
`gsutil du` returns 549266284

**Comment by frankyn** [comment] 2020-04-13 17:38
Thanks @llarco 
Duplicate of: https://github.com/googleapis/python-storage/issues/94

**Closed by frankyn** 2020-04-13 17:38 UTC
Labels: api: storage, duplicate, priority: p2, status: duplicate, type: bug
