### ISSUE TITLE
ConnectionResetError while uploading a file in Firebase Storage

### ISSUE THREAD

**Issue by danbader88** [googleapis/python-storage#291] opened 2020-10-08 06:55 UTC
I am facing following intermittent issue while uploading a file in the Firebase storage from my Django web app-

![connection_error](https://user-images.githubusercontent.com/69597128/95424629-8a7eac80-0960-11eb-840b-4289b8f6e4af.JPG)

The server console with error is as below-
![intermittent_issue](https://user-images.githubusercontent.com/69597128/95424701-a97d3e80-0960-11eb-8066-59c491169eda.JPG)

My code-
![upload_file](https://user-images.githubusercontent.com/69597128/95424862-fa8d3280-0960-11eb-885b-cf4194f734d6.JPG)

where `DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'`

My env is Python 3.7.3, Django 3.1, Firebase, google-cloud-storage==1.31.2
Please suggest how can I fix this issue without a retry option since it may upload a broken file?

**Comment by andrewsg** [comment] 2020-10-08 16:28
Can you clarify what you mean about not wanting to use retry since "it may upload a broken file"? Are you concerned something about the source file may be the cause of the network error?

**Comment by danbader88** [comment] 2020-10-10 07:29
@andrewsg I found for a similar issue, someone told to add a retry option incase of connection closing-
[https://github.com/googleapis/google-cloud-python/issues/5879](url)

**Comment by andrewsg** [comment] 2020-10-12 17:44
I would indeed recommend the use of a retry option. Normally uploads are covered by the standard retry strategy defined in google-resumable-media-python (ex: https://github.com/googleapis/google-resumable-media-python/blob/03c11bae0c43830d539f1e0adcc837a6c88f4e2e/google/resumable_media/_helpers.py#L143). However, it looks like ConnectionError is not considered (only invalid HTTP status returns such as a 500 error are covered). There might be a reason for this; I will investigate.

As a workaround, I'd recommend wrapping your code in an additional retry specifically to catch ConnectionError.

**Comment by andrewsg** [comment] 2020-12-11 20:43
The issue where ConnectionError is not covered by media operation retry policy is now fixed.

**Closed by andrewsg** 2020-12-11 20:43 UTC
Labels: api: storage, priority: p2, type: bug
