### ISSUE TITLE
Example in the code is not relevant

### ISSUE THREAD

**Issue by leahecole** [googleapis/python-storage#1020] opened 2023-04-21 21:02 UTC
I'm migrating this issue here from its spot in https://github.com/GoogleCloudPlatform/python-docs-samples/issues/9750. @Thierrynjike writes,

for this file, https://github.com/googleapis/python-storage/blob/HEAD/samples/snippets/storage_list_files_with_prefix.py from line 26 to 49, the example used is not relevant because the used prefix is the bucket root.
This is my proposition of more relevant example:
Given the following blobs:
a/b
a/c/x
a/b/d/e
a/b/d/f
if you pass 'd/ as the prefix, you'll get back the following blobs:
d/e
d/f
However, if you pass b/ as the prefix, yo'll get back the following blobs
b/d/e
b/d/f

**Comment by cojenco** [comment] 2023-05-02 22:29
Hi @Thierrynjike thank you for the feedback. This example is intended to be a simple directory demonstration and is widely used across language code snippets, as shown [here](https://cloud.google.com/storage/docs/samples/storage-list-files-with-prefix). 

The main purpose is to showcase the (combined) usage of `prefix` and `delimiter` as well as the `blob.prefixes` entity. To enhance readability, we've purposefully written this example with just 2 layers of subdirectory, `prefix ='a/'` being the first level subdirectory. 

While I can see how a detailed example could be more realistic, the major concern is that this would be much more verbose. In the proposition, with more levels of subdirectories, we would have to assign `prefix='a/b/d/'` instead of merely `prefix ='d/'`. The inclusion of a `delimeter` or not would also add complication to the possible outcomes.

**Comment by Thierrynjike** [comment] 2023-05-03 07:33
Hi @cojenco ,
Thanks for the feedback.
I have tested it before opening the issue and it works just by passing `prefix='d/'` . It's exactly what I would like to show with this example. So, no matter the level where your blobs are, you just need to pass the the +1 level object name

**Comment by cojenco** [comment] 2023-05-03 21:23
Based on the API design, the `prefix` parameter filters results to include only **objects whose names begin with this prefix**. When prefix is set, the names of the objects returned in the response are relative to the root of the bucket. That said, the prefix has to be the relative path to the root of the bucket in order to be recognized.

I've also ran multiple tests using this code snippet you've linked. You will get a 200 but an empty response body (no blobs being detected) if you pass in prefix='d/'. Only if you pass in the full  prefix='a/b/d/', will the relevant blobs be included in the response. As this example is working as intended, I'll be closing the issue. Happy to share my bucket directories setup and test results with you if you have further questions.

**Closed** 2023-05-04 16:51 UTC
Labels: api: storage, type: bug, samples
