### ISSUE TITLE
Consolidate extended retry docstring information in docs file, with links

### ISSUE THREAD

**Issue by andrewsg** [googleapis/python-storage#466] opened 2021-06-11 22:27 UTC
Method arguments accepting Retry and ConditionalRetryPolicy have long, detailed docstrings that may be better consolidated in the actual documentation directory and served via a link in the docstring.

**Comment by tseaver** [comment] 2021-06-21 17:04
Duplicate of #455?  That one was closed in #461.

**Comment by cojenco** [comment] 2022-09-07 19:50
This seems to be closed via #461. @andrewsg please reopen if there are other action items.

**Closed by cojenco** 2022-09-07 19:50 UTC
Labels: api: storage, type: docs
