### ISSUE TITLE
Python blob.upload_from_file allocates a lot of memory when passed a StringIO object as file

### ISSUE THREAD

**Issue by Andrei-Paul** [googleapis/python-storage#365] opened 2021-01-23 14:44 UTC
#### Environment details
  - OS: Ubuntu 20.04.1 LTS on WSL2
  - Python version: Python 3.8.5
  - pip version: pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
  - `google-cloud-storage` version: 1.31.0

#### Steps to reproduce

Create StringIO object, fill it with 512MB of text -> Program memory consumption is about 600MB
Get a blob, call blob.upload_from_file(stringIOFile) ->

Expectation:
File is uploaded; Program memory consumption is about 800MB ✔
Reality:
File is uploaded; Program memory consumption is about 2.4GB ❌

#### Steps to produce expected results

Create BytesIO object, wrap it in TextIOWrapper, fill it with 512MB of text -> Program memory consumption is about 600MB
Get a blob, call blob.upload_from_file(bytesIOFileFromUnderWrapper) ->

Expectation:
File is uploaded; Program memory consumption is about 800MB ✔
Reality:
File is uploaded; Program memory consumption is about 800MB ✔

**Comment by frankyn** [comment] 2021-01-25 22:48
@andrewsg this is the issue I mentioned during today's meeting.

**Comment by andrewsg** [comment] 2021-01-25 23:40
Thanks. This looks like a bit of a strange one. I can't imagine why bytes would be handled differently here in any of the top or intermediary layers. I'll have to do some profiling.

**Comment by frankyn** [comment] 2021-01-26 23:43
Hi @Andrei-Paul,

Thanks for filing the issue. I discussed offline with @andrewsg and will pick up this issue.

Could you share how you're measuring memory consumption so I can debug the issue you've encountered?

Thank you for your patience!

**Comment by Andrei-Paul** [comment] 2021-01-27 00:40
Noticed first when I deployed the code as a cloud function and it died with out of memory error at 1gb limit, then at 2gb limit while processing 600 ish MB of data in 512 ish MB batches and  reusing the StringIO 'buffer' (seek 0 + truncate 0)

Debugged in vscode monitoring the process memory consumption with top program. Switched out the StringIO with BytesIO and wrapper, the problem went away.

I'll try to write something to recreate the steps tomorrow™

**Comment by frankyn** [comment] 2021-01-27 00:42
Thanks Andrei! I'll take another look tomorrow when I'm back online.

Frank Natividad | Developer Relations Engineer | Google Cloud Storage

**Comment by Andrei-Paul** [comment] 2021-01-27 15:40
[balloon.zip](https://github.com/googleapis/python-storage/files/5881266/balloon.zip)
balloon.py shows the described behavior.
It needs [ bucketName = ] and [ blobName = ]

Used tracemalloc this time. Results:
**StringIO**
Memory usage before StringIO buffering is 0.000323MB; Peak was 0.000428MB
Memory usage after StringIO buffering is 541.097759MB; Peak was 548.214302MB

Memory usage **before** StringIO upload is **541**.097759MB; Peak was **548**.214302MB
Memory usage **after** StringIO upload is **2148**.338752MB; Peak was **2685**.171595MB

**BytesIO**
Memory usage before BytesIO buffering is 0.001109MB; Peak was 0.001302MB
Memory usage after BytesIO buffering is 551.579326MB; Peak was 551.598622MB

Memory usage **before** BytesIO upload is **551**.579326MB; Peak was **551**.598622MB
Memory usage **after** BytesIO upload is **551**.638175MB; Peak was **761**.387065MB

**Comment by frankyn** [comment] 2021-01-28 22:41
Thanks @Andrei-Paul I'm investigating now. I got held up with a different issue. Thank you for your patience!

**Comment by frankyn** [comment] 2021-01-29 01:31
Short update:

Thanks for making this easy to reproduce. I tried using memory-profiler as recommended by @andrewsg and confused because the memory bloat occurs on when calling `.read()` (seen below).

I attempted to modify the chunk size, but that did not help. I don't think this has to do with the Storage library or relevant layers (resumable media).

I just wanted to share my current status. I'll follow up on Monday when I'm back online.

```
Memory usage before StringIO buffering is 0.000409MB; Peak was 0.000506MB
Memory usage after StringIO buffering is 541.096882MB; Peak was 548.213425MB


Memory usage before StringIO upload is 541.096946MB; Peak was 548.213425MB
chunk size: 262144
[ Top 10 ]
/home/franknatividad/Documents/test-python-storage/testbin36/lib/python3.6/site-packages/google/resumable_media/_upload.py:972: size=2048 MiB, count=2, average=1024 MiB
/home/franknatividad/Documents/test-python-storage/testbin36/lib/python3.6/linecache.py:137: size=132 KiB, count=1289, average=105 B
balloon.py:96: size=128 KiB, count=1, average=128 KiB
/home/franknatividad/Documents/test-python-storage/testbin36/lib/python3.6/posixpath.py:363: size=82.6 KiB, count=563, average=150 B
/home/franknatividad/.pyenv/versions/3.6.4/lib/python3.6/inspect.py:732: size=35.1 KiB, count=561, average=64 B
<frozen importlib._bootstrap_external>:487: size=19.6 KiB, count=207, average=97 B
/home/franknatividad/.pyenv/versions/3.6.4/lib/python3.6/inspect.py:742: size=18.0 KiB, count=1, average=18.0 KiB
/home/franknatividad/.pyenv/versions/3.6.4/lib/python3.6/inspect.py:738: size=18.0 KiB, count=1, average=18.0 KiB
/home/franknatividad/Documents/test-python-storage/testbin36/lib/python3.6/sre_compile.py:579: size=13.2 KiB, count=16, average=847 B
/home/franknatividad/Documents/test-python-storage/testbin36/lib/python3.6/sre_parse.py:416: size=13.2 KiB, count=14, average=968 B
Filename: /home/franknatividad/Documents/test-python-storage/testbin36/lib/python3.6/site-packages/google/resumable_media/_upload.py

Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
   936    571.1 MiB    571.1 MiB           1   @profile
   937                                         def get_next_chunk(stream, chunk_size, total_bytes):
   938                                             """Get a chunk from an I/O stream.
   939                                         
   940                                             The ``stream`` may have fewer bytes remaining than ``chunk_size``
   941                                             so it may not always be the case that
   942                                             ``end_byte == start_byte + chunk_size - 1``.
   943                                         
   944                                             Args:
   945                                                 stream (IO[bytes]): The stream (i.e. file-like object).
   946                                                 chunk_size (int): The size of the chunk to be read from the ``stream``.
   947                                                 total_bytes (Optional[int]): The (expected) total number of bytes
   948                                                     in the ``stream``.
   949                                         
   950                                             Returns:
   951                                                 Tuple[int, bytes, str]: Triple of:
   952                                         
   953                                                   * the start byte index
   954                                                   * the content in between the start and end bytes (inclusive)
   955                                                   * content range header for the chunk (slice) that has been read
   956                                         
   957                                             Raises:
   958                                                 ValueError: If ``total_bytes == 0`` but ``stream.read()`` yields
   959                                                     non-empty content.
   960                                                 ValueError: If there is no data left to consume. This corresponds
   961                                                     exactly to the case ``end_byte < start_byte``, which can only
   962                                                     occur if ``end_byte == start_byte - 1``.
   963                                             """
   964    571.1 MiB      0.0 MiB           1       import tracemalloc
   965                                         
   966    571.1 MiB      0.0 MiB           1       start_byte = stream.tell()
   967    571.1 MiB      0.0 MiB           1       print("chunk size: {}".format(chunk_size))
   968    571.1 MiB      0.0 MiB           1       from io import StringIO
   969    571.1 MiB      0.0 MiB           1       if total_bytes is not None and start_byte + chunk_size >= total_bytes > 0:
   970                                                 payload = stream.read(total_bytes - start_byte)
   971                                             else:
------->>>   972   2104.7 MiB   1533.7 MiB           1           payload = stream.read(chunk_size)
   973   2104.7 MiB      0.0 MiB           1       end_byte = stream.tell() - 1
   974   2104.7 MiB      0.0 MiB           1       snapshot = tracemalloc.take_snapshot()
   975   2104.7 MiB      0.0 MiB           1       top_stats = snapshot.statistics('lineno')
   976                                         
   977   2104.7 MiB      0.0 MiB           1       print("[ Top 10 ]")
   978   2104.7 MiB      0.0 MiB          11       for stat in top_stats[:10]:
   979   2104.7 MiB      0.0 MiB          10           print(stat)
   980   2104.7 MiB      0.0 MiB           1       num_bytes_read = len(payload)
   981   2104.7 MiB      0.0 MiB           1       if total_bytes is None:
   982   2104.7 MiB      0.0 MiB           1           if num_bytes_read < chunk_size:
   983                                                     # We now **KNOW** the total number of bytes.
   984                                                     total_bytes = end_byte + 1
   985                                             elif total_bytes == 0:
   986                                                 # NOTE: We also expect ``start_byte == 0`` here but don't check
   987                                                 #       because ``_prepare_initiate_request()`` requires the
   988                                                 #       stream to be at the beginning.
   989                                                 if num_bytes_read != 0:
   990                                                     raise ValueError(
   991                                                         u"Stream specified as empty, but produced non-empty content."
   992                                                     )
   993                                             else:
   994                                                 if num_bytes_read == 0:
   995                                                     raise ValueError(
   996                                                         u"Stream is already exhausted. There is no content remaining."
   997                                                     )
   998                                         
   999   2104.7 MiB      0.0 MiB           1       content_range = get_content_range(start_byte, end_byte, total_bytes)
  1000   2104.7 MiB      0.0 MiB           1       return start_byte, payload, content_range
```

**Comment by frankyn** [comment] 2021-02-03 19:17
HI @Andrei-Paul,

I did additional research and found that it's not directly correlated to the python-storage package and in the Python std library.

I reproduced the memory consumption by swapping out the Cloud Storage upload by only reading a 100MiB segment:

```
    seed(0)

    tracemalloc.start()

    with StringIO() as stringIOFile:
        writer = csv.writer(stringIOFile, doublequote=False)

        current, peak = tracemalloc.get_traced_memory()
        print(f"\nMemory usage before StringIO buffering is {current / 10**6}MB; Peak was {peak / 10**6}MB")
        while True:
            for index in range(10):
                row[index] = str(random())

            writer.writerow(row)

            if stringIOFile.tell() > int(1073741824 / 2):
                current, peak = tracemalloc.get_traced_memory()
                print(f"Memory usage after StringIO buffering is {current / 10**6}MB; Peak was {peak / 10**6}MB\n")
                stringIOFile.seek(0)
                current, peak = tracemalloc.get_traced_memory()
                print(f"\nMemory usage before StringIO upload i s {current / 10**6}MB; Peak was {peak / 10**6}MB")
                part = stringIOFile.read(2**20 * 100)
                #part = uploadBlob(bucketName, blobName, stringIOFile)
                current, peak = tracemalloc.get_traced_memory()
                print(f"Memory usage after StringIO upload is {current / 10**6}MB; Peak was {peak / 10**6}MB\n")
                stringIOFile.seek(0)
                stringIOFile.truncate(0)

                break

    tracemalloc.stop()
```

I'm not sure what the difference is between the use-cases (ByteIO/StringIO).

I'm closing because it's not directly related to the python-storage library. Thank you for your patience.

**Closed by frankyn** 2021-02-03 19:17 UTC
Labels: api: storage, external, status: investigating, type: question

**Comment by Andrei-Paul** [comment] 2021-02-03 19:34
Ok, thank you for your time.
