### ISSUE TITLE
Retry Didn't occurred

### ISSUE THREAD

**Issue by nitishxp** [googleapis/python-storage#780] opened 2022-04-27 17:59 UTC
Cloud function runtime python39
Lib - google-cloud-storage==2.1.0

```
Expecting value: line 1 column 1 (char 0) Traceback (most recent call last):  File "/workspace/fn/services.py", line 188, in activate_client self.bucket: storage.Bucket = self.gcs.get_bucket("bucket_name") File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/storage/client.py", line 780,
 in get_bucket bucket.reload( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/storage/bucket.py", line 1029, in reload super(Bucket, self).reload( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/storage/_helpers.py", line 232,
 in reload api_response = client._get_resource( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/storage/client.py", line 364, 
in _get_resource return self._connection.api_request( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/storage/_http.py", line 80, 
in api_request return call() File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/api_core/retry.py", line 286, 
in retry_wrapped_func return retry_target( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/api_core/retry.py", line 189, in retry_target return target() File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/_http/__init__.py", line 482, 
in api_request response = self._make_request( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/_http/__init__.py", line 341, in _make_request return self._do_request( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/_http/__init__.py", line 379,
 in _do_request return self.http.request( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/auth/transport/requests.py", line 476, in request self.credentials.before_request(auth_request, method, url, request_headers) 
File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/auth/credentials.py", line 133, in before_request self.refresh(request) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/oauth2/service_account.py", line 408, 
in refresh access_token, expiry, _ = _client.jwt_grant( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/oauth2/_client.py", line 193, 
in jwt_grant response_data = _token_endpoint_request(request, token_uri, body) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/oauth2/_client.py", line 161,
 in _token_endpoint_request response_status_ok, response_data = _token_endpoint_request_no_throw( File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/oauth2/_client.py", line 121, 
in _token_endpoint_request_no_throw response_data = json.loads(response_body) File "/opt/python3.9/lib/python3.9/json/__init__.py", line 346, in loads return _default_decoder.decode(s) File "/opt/python3.9/lib/python3.9/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/opt/python3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by JesseLovelace** [comment] 2022-04-29 18:19
Hi,

We need a little more info to reproduce this bug. Please provide the code sample from the function and let us know exactly which operation is failing to retry, and show us how you're configuring retries and what you're expecting to see.

**Comment by nitishxp** [comment] 2022-04-29 18:29
@JesseLovelace 

Below is the code

client = storage.Client()
bucket = client.get_bucket(name)

Since from the logs you can see the there file fetching auth token due to jsonDecodeError issue code just crashed, instead a retry should be done

https://github.com/googleapis/python-storage/blob/main/google/cloud/storage/retry.py#L46

**Comment by ddelgrosso1** [comment] 2022-05-02 13:59
Hi @nitishxp from what you have said and the exception you provided it appears the code provided had a `jsonDecodeError` as opposed to a `TransportError`. Since a `jsonDecodeError` is not an error from the HTTP transport layer I would not expect this issue to retry.

**Comment by nitishxp** [comment] 2022-05-02 14:04
@ddelgrosso1 then how should we handle this? since many times In production environment I have started to seeing this issue.

**Comment by ddelgrosso1** [comment] 2022-05-02 14:21
@nitishxp I will speak with some other members of the team and try to get a better idea of why this might be happening. Just so I have all the information, are you utilizing any kind of custom endpoint or anything that might help debug this issue further?

**Comment by nitishxp** [comment] 2022-05-02 14:34
No @ddelgrosso1 I am not modifying any paramaters

**Comment by ddelgrosso1** [comment] 2022-05-02 19:42
@nitishxp I setup a basic cloud function utilizing the same runtime and code snippet you provided. After executing it several times I did not seem to have any issue with the decoder. How often does this issue appear for you? Is there any other code you could provide that might help debug further?

**Comment by nitishxp** [comment] 2022-05-04 04:46
@ddelgrosso1 We have find this error more frequently occurring in australia-southeast1 then any other region

**Comment by ddelgrosso1** [comment] 2022-05-04 14:41
@nitishxp how frequently is this happening? How many instances of the function are running at any time? Are the buckets also located in australia-southeast1?

**Comment by nitishxp** [comment] 2022-05-04 14:53
in the last 10 days there were 3-4 occurrences, yes bucket and Cloud function both are in same region.

**Comment by ddelgrosso1** [comment] 2022-05-04 18:49
@nitishxp it appears that this issue is the same as https://github.com/googleapis/google-auth-library-python/issues/857. Storage is also a consumer of the auth library. Since this issue is already being tracked / worked on in auth I am going to close this issue. If you feel that this is incorrect, please feel free to reopen.

**Closed by ddelgrosso1** 2022-05-04 18:49 UTC
Labels: api: storage, needs more info, type: bug, priority: p2
