### ISSUE TITLE
invalid_grant

### ISSUE THREAD

**Issue by lechen26** [googleapis/python-storage#369] opened 2021-02-03 12:48 UTC
Hi

we are using google service account to access cloud stoage on one of our python projects.

nothing has changes on the service account we are using but recently we've started to see this intermittent error:
```
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT Signature.', '{"error":"invalid_grant","error_description":"Invalid JWT Signature."}')
```

it does not happen all the time but from time to time. like it failed to refresh the token but i dont understand why.
what can be the reason for this?

thanks
CL

**Comment by frankyn** [comment] 2021-02-03 19:43
Hi @lechen26,

Thanks for filing the issue.
This is a duplicate of #17, which is being looked at here: https://github.com/googleapis/google-auth-library-python/issues/261

**Comment by fcollman** [comment] 2021-02-03 21:23
I don't think this is the same error, the exception looks different.  We are also experiencing the same error, again on code that did not change, only upgrades to underlying google packages. 

The exception listed in this isssue..
```
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT Signature.', '{"error":"invalid_grant","error_description":"Invalid JWT Signature."}')
``` 
The exception listed in #17 
```
google.auth.exceptions.RefreshError: ('invalid_grant: reauth related error (rapt_required)', '{\n  "error": "invalid_grant",\n  "error_description": "reauth related error (rapt_required)",\n  "error_subtype": "rapt_required"\n}')
```

**Comment by fcollman** [comment] 2021-02-03 21:45
I think this issue is actually covered here
https://github.com/googleapis/google-auth-library-python/issues/667

and might be related to this underlying RSA issue
https://github.com/sybrenstuvel/python-rsa/issues/173

**Comment by frankyn** [comment] 2021-02-03 22:40
Ah, good call out, my mistake. let's reopen to keep track

**Comment by lechen26** [comment] 2021-02-07 07:34
thanks @fcollman , exactly , we havent changed anything except we've upgraded our cluster.
i saw the RSA issue, but to be honest i wasnt sure its related as we are not using this package.

is this something the google-cloud-storage using?

thanks

**Comment by lechen26** [comment] 2021-02-07 08:03
i've checked with pipdeptree its indeed the case.
thanks!

**Comment by busunkim96** [comment] 2021-02-08 16:11
Just to make things explicit, if you're running into this please explicitly pin to `rsa==4.6` in your requirements.txt.

For context, `google-cloud-storage` depends on `google-auth` which depends on `rsa`.

**Comment by tritone** [comment] 2021-02-09 03:46
Thanks for clarifying @busunkim96 -- I'll go ahead and close this issue.

**Closed by tritone** 2021-02-09 03:46 UTC
Labels: api: storage, priority: p2, type: bug
